### ISSUE TITLE
Can't turn TV on

### ISSUE THREAD

**Issue by outoftheblue62** [FeLiNa22/amazon-alexa-lg-tv#3]
Hi again :)

Everything is working great, tested many of the functions.  The only function that I can't get to work is to have Alexa power on my TV..

After I ask Alexa to turn TV on, I see the following in terminal:

```
messy : {"deviceId":"5c4bac8c398dcc587988bd0f","action":"setPowerState","value":"ON"}
ERROR LOL : Connection is already closed.
### closed ###
### Initiating new websocket connection ###
```

**Comment by FeLiNa22** [comment]
Yes I have been having the same problem very recently, I believe it may be due to the new LG webOS update which has stopped this feature from working with my program, I will definitely be looking for away around this problem, but as for now, you may just have to bear with. 

I am thinking that the only to turn the TV back might be using WOL packet sending, which becomes a complicated process. If you have any ideas I am open to suggestions.

**Comment by nxferenc** [comment]
In Alexa.py there is a section:
```
    if(action == "setPowerState") :
        lgtv.LGparser(['off'])
```
Change it to:
```
    if(action == "setPowerState") :
	power = json_data["value"]
	if (power == "OFF"):
	    lgtv.LGparser(['off'])
	else:
	    lgtv.LGparser(['on'])
```

**Comment by FeLiNa22** [comment]
Hi nxferenc, thank you for this solution, 

I have tried this in the past, and it works fine for a while, however after the TV has been turned off for a while (2-3 hours) an issue rises as the WOL packet sender will not turn on the TV because the router no longer recognises the device. I am still searching for a solution to this.

If you have any ideas to tackle this problem, please let me know :)

**Comment by nxferenc** [comment]
My TV was turned off all day long and now turned on with alexa. LG 49UK6200
I don't know if it helps but I have static IP on TV.

**Comment by FeLiNa22** [comment]
Oh, fairs. Perhaps my router is just blocking it. If it is working for you, then that is perfect :)

**Comment by outoftheblue62** [comment]
Hi - I updated the code from nxferenc (Thanks!)

I can turn the TV off and on, however I need to keep asking Alexa to turn the TV off to turn on.  See output below for example.

Turning TV off (success)
```
### Initiating new websocket connection ###
messy : {"deviceId":"5c4bac8c398dcc587988bd0f","action":"setPowerState","value":"OFF"}
{"type": "response", "id": "0", "payload": {"returnValue": true}}
{"closing": {"reason": "", "code": 1000}}
```
Turning TV on (not successful)
```
messy : {"deviceId":"5c4bac8c398dcc587988bd0f","action":"setPowerState","value":"ON"}
```
While TV is off, ask Alexa to turn TV off (TV turns on)
```
messy : {"deviceId":"5c4bac8c398dcc587988bd0f","action":"setPowerState","value":"OFF"}
{"type": "response", "id": "0", "payload": {"returnValue": true}}
{"closing": {"reason": "", "code": 1000}}
```
Turning TV off (successful)
```
messy : {"deviceId":"5c4bac8c398dcc587988bd0f","action":"setPowerState","value":"OFF"}
{"type": "response", "id": "0", "payload": {"returnValue": true}}
{"closing": {"reason": "", "code": 1000}}
```
TV off, ask Alexa to turn TV off (TV turns on)
```
messy : {"deviceId":"5c4bac8c398dcc587988bd0f","action":"setPowerState","value":"OFF"}
{"type": "response", "id": "0", "payload": {"returnValue": true}}
{"closing": {"reason": "", "code": 1000}}
```
Not sure why the TV turns on when I ask Alexa to turn off?

**Comment by FeLiNa22** [comment]
Hi outoftheblue62, I have updated the Alexa.py, if you clone and replace this file, then try the program, see if the error persists. 

If it does, then send me the error report, thank you !
